export const FETCH_PLANET = "FETCH_PLANET";
export const FETCH_PLANET_SUCCESS = "FETCH_PLANET_SUCCESS";
export const FETCH_PLANET_FAILED = "FETCH_PLANET_FAILED";

export const FETCH_PLANET_DETAIL = "FETCH_PLANET_DETAIL";
export const FETCH_PLANET_DETAIL_SUCCESS = "FETCH_PLANET_DETAIL_SUCCESS";
export const FETCH_PLANET_DETAIL_FAILED = "FETCH_PLANET_DETAIL_FAILED";
